# Generated by Django 5.0 on 2023-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publisher', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('PageCount', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('ShelfLocation', models.CharField(max_length=100)),
                ('PublishedDate', models.DateField()),
                ('IsInstock', models.BooleanField()),
                ('DateCheckedOut', models.DateField()),
            ],
        ),
    ]
